#!/command/with-contenv bash

# Set our working directory
cd /dist || exit

ARGS=(--endpoint http://127.0.0.1:4000 --introspection --sse-address 0.0.0.0 --sse-port 5001)

if [[ -z "$APOLLO_GRAPH_REF" || -z "$APOLLO_KEY" ]]; then
  ARGS+=(--schema /dist/schema.graphql)
else
  ARGS+=(--uplink)
fi

exec /dist/apollo-mcp-server "${ARGS[@]}"

