#!/command/with-contenv bash

# Set our working directory
cd /opt || exit

ARGS=(--config /config/router_config.yaml)

if [[ -z "$APOLLO_GRAPH_REF" || -z "$APOLLO_KEY" ]]; then
  ARGS+=(--supergraph /config/schema.graphql)
fi
if [[ -n "$DEV_MODE" ]]; then
  ARGS+=(--dev)
fi

exec /opt/router "${ARGS[@]}"
