# yaml-language-server: $schema=https://github.com/apollographql/apollo-mcp-server/releases/download/v0.6.0/config.schema.json

################################################################################
# Example MCP configuration
#
# Note: Refer to the official documentation for info on what should be present
# https://www.apollographql.com/docs/apollo-mcp-server/command-reference
################################################################################

# If you have custom scalars that you wish to use in your operations / schema, use the following
# configuration
#
# ```yaml
# custom_scalars: /config/custom_scalars.graphql
# ```

# Use uplink for operations
#
# Note: If you wish to use files inside the container instead, use the following configuration:
#
# ```yaml
# operations:
#   source: local
#   paths:
#   - /config/operations
# ```
#
# Note: If you wish to use a persisted query manifest instead, use the following configuration:
#
# ```yaml
# operations:
#   source: manifest
#   path: /config/persisted_queries_manifest.json
# ```
operations:
  source: uplink

# Use uplink for schema information
#
# Note: If you wish to use a file inside the container instead, use the following configuration:
#
# ```yaml
# schema:
#   source: local
#   path: /config/api_schema.graphql
# ```
schema:
  source: uplink

# Configure the MCP server to listen for streamable HTTP messages on port 5000
# for all addresses
transport:
  type: streamable_http
  address: "0.0.0.0"
  port: 5000
